name: Deploy Preview to Netlify

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy Message (visible in Netlify)'

jobs:
  deploy-preview:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Build
        run: yarn build

      - name: Set Deploy message for a Pull Request event
        run: echo "DEPLOY_MSG='#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}'" >> $GITHUB_ENV
        if: "${{ github.event.pull_request.title != '' }}"

      - name: Set Deploy message for a Workflow Dispatch
        run: echo "DEPLOY_MSG='Manual Trigger - ${{ github.event.inputs.tags.description }}'" >> $GITHUB_ENV
        if: "${{ github.event.inputs.tags.description != '' }}"


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          deploy-message: ${{env.DOCKER_IMAGE_NAME}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
